CC=g++
CFLAGS=-I.
DEPS = ElementaryParticle.h

%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

analyzer: analyzer.o ElementaryParticle.o
	$(CC) -o analyzer analyzer.o ElementaryParticle.o

clean:
	rm -rf *.o analyzer
